### ISSUE TITLE
Ctrl+c bug?

### ISSUE THREAD

**Issue by mibzman** [abrowne2/cpp_efficiency#3]
In sublime this morning whenever I used Ctrl+c to copy text I would get
```
--------------
changes have been made, would you like to save?
--------------
```
instead of the proper text.
Unable to reproduce because I don't want to
resolved by restarting the machine

idk if it has anything to do with cpp_efficiency, it was in a .go file

**Comment by abrowne2** [comment]
I'll check it when I can.

**Comment by mibzman** [comment]
this is a sublime bug: https://github.com/SublimeTextIssues/Core/issues/329
